
service: serverlessdemo
plugins:
  - serverless-deployment-bucket
  - serverless-pseudo-parameters
# app and org for use with dashboard.serverless.com
# app: serverlessdemo
# org: chandureddy123

provider:
  name: aws
  runtime: nodejs10.x
  deploymentBucket:
    name: serverlesschandu
    serverSideEncryption: AES256
  apiName: serverlessdemo
# you can overwrite defaults here
  stage: dev
  region: us-west-2
  # role: arn:aws:iam::797118203836:role/lambda_basic_execution

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:service}_users_data_${opt:stage}

  environment:
    TableName: ${self:service}_users_data_${opt:stage}
    Environment: Dev

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  usercreate:
    handler: users.create
    events:
      - http:
            path: /user/create
            method: post
  userget:
    handler: users.list
    events:
      - http:
            path: /user/get
            method: get
  userdel:
    handler: users.delete
    events:
      - http:
          path: /user/delete
          method: post
  userupdate:
    handler: users.update
    events:
      - http:
          path: /user/update
          method: post

resources:
  Resources:
    UserData:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}_users_data_${opt:stage}
        AttributeDefinitions:
           - AttributeName: Name
             AttributeType: S
        BillingMode: 'PAY_PER_REQUEST'
        KeySchema:
          - AttributeName: Name
            KeyType: HASH
        Tags:
          - Key: 'Owner'
            Value: 'ChanduReddy'
          - Key: 'Environment'
            Value: 'Dev' 
      